"use client";
import { ArrowDown, CircleDot, GitBranch } from "lucide-react";
export function CausalGraph() {
  const items=[["HUMAN","Task policy","white"],["FinanceBot","Summarize invoices","blue"],["SEND_EMAIL","External destination","red"],["Scope mismatch","Intent mismatch","red"],["Risk 96","DENY","red"]];
  return <div className="flex flex-col items-center gap-2 py-5">{items.map((x,i)=><div key={i} className="flex flex-col items-center">{i>0&&<ArrowDown size={14} className="mb-2 text-white/20"/>}<div className={"w-full max-w-[420px] rounded-xl border px-4 py-3 "+(x[2]==="red"?"border-[#ff717d]/20 bg-[#ff717d]/[.06]":x[2]==="blue"?"border-[#7aa2ff]/20 bg-[#7aa2ff]/[.06]":"border-white/10 bg-white/[.025]")}><div className="text-[10px] uppercase tracking-[.12em] text-white/35">{x[0]}</div><div className="mt-1 text-sm font-medium">{x[1]}</div></div></div>)}</div>
}
export function DelegationGraph(){return <div className="grid gap-3 md:grid-cols-3"><Node icon={<CircleDot/>} title="Human" meta="root authority"/><Node icon={<GitBranch/>} title="FinanceAgent" meta="payment ≤ ₹500"/><Node icon={<CircleDot/>} title="InvoiceReader" meta="payment ≤ ₹300"/></div>}
function Node({icon,title,meta}:{icon:React.ReactNode;title:string;meta:string}){return <div className="rounded-xl border border-white/10 bg-white/[.025] p-4 text-center"><div className="mx-auto flex h-9 w-9 items-center justify-center rounded-lg border border-white/10 text-white/45">{icon}</div><div className="mt-3 text-sm font-medium">{title}</div><div className="mono mt-1 text-[10px] text-white/35">{meta}</div></div>}
export function ArchitectureFlow(){const steps=["Human","Pass Issuer","AI Agent + Signer","AgentPass Gateway","Identity","Proof","Scope","Budget","Intent","Behavior","Risk","Decision","Vault / Broker","Tool"];return <div className="grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-7">{steps.map((s,i)=><div key={s} className="relative rounded-xl border border-white/10 bg-white/[.025] p-3 text-center"><div className="mono text-[9px] text-white/25">{String(i+1).padStart(2,"0")}</div><div className="mt-2 text-xs font-medium">{s}</div>{i<steps.length-1&&<div className="absolute -right-2 top-1/2 hidden h-3 w-3 -translate-y-1/2 rotate-45 border-r border-t border-white/20 lg:block"/>}</div>)}</div>}
